### ISSUE TITLE
Ban: Banned user can still view banning user's posts in banning user's feed or in group

### ISSUE THREAD

**Issue by smallq-git** [pepyatka/pepyatka-html#523]
If user2 is blocked, they should not be able to see user1's posts in homefeed, user1's feed or any group's feed.

Right now it's possible to view posts in user1's feed (https://github.com/pepyatka/pepyatka-html/issues/522) AND in group's feed.

**Comment by berkus** [comment]
Related https://github.com/pepyatka/pepyatka-html/issues/499

**Comment by smallq-git** [comment]
fixed. banning user doesn't see banned user's posts in the group:
![image](https://cloud.githubusercontent.com/assets/7983303/8441977/835c497e-1f84-11e5-8eb8-efc539453c0d.png)

and profile appears empty.

**Comment by smallq-git** [comment]
a-nope. Still happens in real-time.

**Comment by clbn** [comment]
Still can reproduce on micropeppa (realtime part only):

Pre-condition:
1. User-A and User-B are both subscribed to Group-C.
2. User-A has banned User-B.

Steps:
1. Open Group-C's feed as User-A in one browser.
2. Open Group-C's feed as User-B in another browser.
3. Post to the group as User-A.

Expected:
User-B does not see any new posts show up in the Group-C.

Actual:
User-B sees new posts from User-A on Group-C's page (as realtime updates). After reload they dissappear.

**Comment by clbn** [comment]
@epicmonkey Still can reproduce it with the latest ^ script. I suppose pepyatka/pepyatka-server@023b81e90dbe76f2f65d01b32fba80bfd37affbe didn't fix it.

**Comment by smallq-git** [comment]
https://micropeppa.freefeed.net/cheese/48338790-c138-4a21-885f-efbaa3506e75
User3 has created this post after banning user1. Note that user1 was able to not only see the post but participate in a rather heated discussion with user2 and help reproduce a bug. After page refresh they've lost the post.
